services:
    db:
        container_name: api-database
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        ports:
            - "5432:5432"
    api:
        build: .
        depends_on:
            -   db
        ports:
            - "3000:3000"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        links:
            - db